
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - "./configs/nginx/conf.d:/etc/nginx/conf.d"
      - "./static:/usr/share/nginx/html"
    depends_on:
      - backend

  backend:
    build:
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - DB_NAME=flexive
      - DB_PORT=5432
    volumes:
      - "./configs:/app/configs"
    depends_on:
      - db
      - redis

  db:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: flexive
    volumes:
      - ./migrations/pg:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
